### PR TITLE
Taxonomy models

### PR DESCRIPTION
**Pull request by kaedroho**
Moving schools, programmes and areas into snippets

### CODE REVIEW

**Comment by kaedroho** [comment]
@balazs-endresz please could you review?

**Comment by kaedroho** [comment]
On staging

**Comment by balazs-endresz** [comment]
I'm not sure about having schools with a year field. Are the schools likely to change every year?

And when we have a page related to a school would we use a snippet chooser, or specify a school-slug? Because only the slug would be independent of the year, and refer to a school in general.

**Comment by balazs-endresz** [comment]
It would increase the complexity of the UI but I'd be tempted to add an SchoolYear (or AcademicYear) model between schools and programmes (and remove the year field from School).

And I wonder if we would want to allow a Programme snippet to be associated with multiple schools/years. I guess that depends on whether we want to have year-specific programme pages or not.

**Comment by kaedroho** [comment]
Good point. They want the abilty to add, remove and rename schools/programmes without affecting previous years and they also want a school/programme to link up properly with previous years even if the name has changed.

Currently, when they rename schools/programmes all old content will be updated and keeping it that way would simplify things a lot.

**Comment by balazs-endresz** [comment]
OK, so this would provide School and Programme snippets that are both year-specific. And we can still use slugs to refer to a school or programme in general, which is probably easier than adding extra layers of models anyway.

I think the problem previously wasn't with using slugs but a slug in itself not being year-specific, if that makes sense. So this solves that issue and we'll have both. We'll just have to pay attention to which one to use on a page. I guess typically we'd be referring to a snippet to keep last year's page as well.

**Comment by balazs-endresz** [comment]
> want a school/programme to link up properly with previous years even if the name has changed.

But for schools and programmes to be linked up throughout the years we'd need the slugs to stay the same, so that might be a problem.

**Comment by kaedroho** [comment]
> But for schools and programmes to be linked up throughout the years we'd need the slugs to stay the same, so that might be a problem.

The whole idea of the slugs is that they stay the same even if the display name changes. A little worried they might forget that though.

**Comment by balazs-endresz** [comment]
I'm a bit worried that sometimes the name change can be quite significant, in which case they would understandably want to change the slugs too.  This might be unlikely though, the only thing like that I remember was when the jewellery & metal programme name changed. That's also when we added multiple programmes for programme pages. See related codebase ticket. But if RCA is okay with slugs not changing that will be fine. 

We could also add some UI tweaks to help keep slugs in order: e.g.  warn if there's a similar slug in use (python fuzzywuzzy).

**Comment by kaedroho** [comment]
I've made a couple of changes:
 - Moved year field from school to programme
 - Converted programme into a separate snippet

This means that schools are fixed for all years but programmes still have to be copied year-on-year (as they are often changed). I think this would simplify some of the logic rewriting.

**Comment by kaedroho** [comment]
I've added a new model ``SchoolHistoricalDisplayName``. They really want the ability to change school names over time without old data being affected.

The idea of this model is that whenever the name is changed, a record is added to note the old name and when it was changed. We would query this model from the frontend. I think this is a lot less complicated than making schools year-specific like programmes are.

I still think programmes should be year-specific though, as they add/remove them much more often that the other taxonomy models.

**Comment by balazs-endresz** [comment]
I'm happy with the year-specific programmes but is it really just the name of the school that we want to keep historical records of? Is that going to show up on year specific SchoolPages? If so, then we might be better off with a new SchoolPage instance each year - that would keep all the fields too.

**Comment by kaedroho** [comment]
> but is it really just the name of the school that we want to keep historical records of?

What do you have in mind? the school taxonomy field only has the name and slug at the moment, and the slug shouldn't change year by year.

> Is that going to show up on year specific SchoolPages?

Not sure what you mean by "year specific SchoolPages". The main use for this would be for displaying the correct school name on old student profiles.

**Comment by balazs-endresz** [comment]
> The main use for this would be for displaying the correct school name on old student profiles.

If it's just for that then it's fine. I was thinking that other school related fields might change each year, like the description for a school. So if we created a new SchoolPage every year that would act the same way as SchoolHistoricalDisplayName: it would keep a record of the school name and other school related fields too. But I guess this isn't really necessary, so SchoolHistoricalDisplayName will do.

And we should have some help text for the programme slug field too, to explain that the slug shouldn't change each year if it's referring to the same programme.

**Comment by kaedroho** [comment]
After working on integrating this with the rest of the site, i'm now thinking of removing the graduation year from programme and instead using a "historical name" thing like schools.

This would mean that they can't accidentally change the slug between years, and research students are can have a blank graduation year.

**Comment by kaedroho** [comment]
Changes mentioned yesterday are now done. The schema is now as follows:

Area:
 - slug
 - display name

School
 - slug
 - display name

SchoolHistoricalName
  # Used for finding old names of schools when displaying old student profiles
 - school (FK to School)
 - end_year
 - display_name

Programme
 - school (FK to School)
 - slug
 - display name
 - disabled (boolean field. When set, this programme will be removed from dropdowns for new content. Q: are there any advantages to using start_year/end_year fields for this instead?)

ProgrammeHistoricalName
  # Same idea as SchoolHistoricalName
 - programme (FK to Programme)
 - end_year
 - display_name

**Pull request merged**
